export const wh4e = {
  classes: {
    theDeft: "wh4e.class.theDeft",
    theStrong: "wh4e.class.theStrong",
    theWise: "wh4e.class.theWise",
    theBrave: "wh4e.class.theBrave",
    theFortunate: "wh4e.class.theFortunate",
  },
  damageDice: {
    oneDmg: "wh4e.damageDice.oneDmg",
    d6minus3: "wh4e.damageDice.d6minus3",
    d6minus2: "wh4e.damageDice.d6minus2",
    d6minus1: "wh4e.damageDice.d6minus1",
    d6: "wh4e.damageDice.d6",
    d6plus1: "wh4e.damageDice.d6plus1",
    d6plus2: "wh4e.damageDice.d6plus2",
    d6plus3: "wh4e.damageDice.d6plus3",
    d6plus4: "wh4e.damageDice.d6plus4",
    Twod6minus2: "wh4e.damageDice.Twod6minus2",
    Twod6minus1: "wh4e.damageDice.Twod6minus1",
    Twod6: "wh4e.damageDice.Twod6",
    Twod6plus1: "wh4e.damageDice.Twod6plus1",
    Twod6plus2: "wh4e.damageDice.Twod6plus2",
    Twod6plus3: "wh4e.damageDice.Twod6plus3",
    Twod6plus4: "wh4e.damageDice.Twod6plus4",
    Threed6minus2: "wh4e.damageDice.Threed6minus2",
    Threed6minus1: "wh4e.damageDice.Threed6minus1",
    Threed6: "wh4e.damageDice.Threed6",
    Threed6plus1: "wh4e.damageDice.Threed6plus1",
    Threed6plus2: "wh4e.damageDice.Threed6plus2",
    Threed6plus3: "wh4e.damageDice.Threed6plus3",
    Threed6plus4: "wh4e.damageDice.Threed6plus4",
  },
  weaponWeightTypes: {
    regular: "wh4e.weightTypes.regular",
    heavy: "wh4e.weightTypes.heavy",
    minor: "wh4e.weightTypes.minor",
    small: "wh4e.weightTypes.small",
    negligible: "wh4e.weightTypes.negligible",
  },
  gearWeightTypes: {
    regular: "wh4e.weightTypes.regular",
    heavy: "wh4e.weightTypes.heavy",
    minor: "wh4e.weightTypes.minor",
    small: "wh4e.weightTypes.small",
    negligible: "wh4e.weightTypes.negligible",
    noEncumbrance: "wh4e.weightTypes.noEncumbrance",
  },
  roFShotsPerRound: {
    none: "wh4e.misc.none",
    oneInFour: "wh4e.roFShotsPerRound.oneInFour",
    oneInThree: "wh4e.roFShotsPerRound.oneInThree",
    oneInTwo: "wh4e.roFShotsPerRound.oneInTwo",
    one: "wh4e.roFShotsPerRound.one",
    three: "wh4e.roFShotsPerRound.three",
  },
  abilityTypes: {
    attunement: "wh4e.abilityType.attunement",
    combatOption: "wh4e.abilityType.combatOption",
    miracle: "wh4e.abilityType.miracle",
    quirk: "wh4e.abilityType.quirk",
    species: "wh4e.abilityType.species",
    vocation: "wh4e.abilityType.vocation",
    affiliation: "wh4e.abilityType.affiliation",
  },
  coinTypes: {
    gp: "wh4e.coinType.gp",
    sp: "wh4e.coinType.sp",
    cp: "wh4e.coinType.cp",
  },
  armourClasses: {
    0: "0",
    1: "1",
    2: "2",
    3: "3",
    4: "4",
    5: "5",
    6: "6",
    7: "7",
    8: "8",
    9: "9",
    plusOne: "+1",
    plusTwo: "+2",
    plusThree: "+3",
    minusOne: "-1",
    minusTwo: "-2",
    minusThree: "-3",
    special: "wh4e.item.special",
  },
  monsterArmourClasses: {
    0: "0",
    1: "1",
    2: "2",
    3: "3",
    4: "4",
    5: "5",
    6: "6",
    7: "7",
    8: "8",
    9: "9",
  },
};
